### ISSUE TITLE
Proposed updates/clarifications

### ISSUE THREAD

**Issue by enygren** [richsalz/draft-ietf-uta-rfc6125bis#101]
Some comments on a read-through if not too late:

1) On DNS names starting with Labels:

> historically this rule was also intended to apply to all labels in a domain name (see [Section 2.3.1](https://rfc-editor.org/rfc/rfc1035#section-2.3.1) of [[DNS-NAMES](https://www.rfc-editor.org/rfc/rfc1035)]), although that is not always the case in practice.

This should probably be more clear that domain names are explicitly allowed to start with digits.  As per  https://datatracker.ietf.org/doc/html/rfc1123#section-2.1 and https://datatracker.ietf.org/doc/html/rfc2181#section-11 clearly update this.  For example from the former clearly states:
"One aspect of host name syntax is hereby changed: the restriction on the first character is relaxed to allow either a letter or a digit.  Host software MUST support this more liberal syntax"

2) On the Web example:

>Consider a simple website at www.example.com, which is not discoverable via DNS SRV lookups. Because HTTP does not specify the use of URIs in server certificates, a certificate for this service might include only a DNS-ID of www.example.com.
> Consider the same website, which is reachable by a fixed IP address of 2001:db8::5c. The certificate might include this value in an IP-ID to allow clients to use the fixed IP address as a reference identity.

This would not be the same "website".  In particular, the web origin (rfc6454) is the tuple of scheme, authority, and port.  Since the authority is different (ie, the IP vs the hostname) they would be distinct.   If we're going to include this example, we should be clear that https://www.example.com/ and https://[2001:db8::5c]/ might be multi-tenant on the same server but are different web origins (ie, different "websites")

3) Example in 6.1.2 (nit)
Per https://www.iab.org/2016/11/07/iab-statement-on-ipv6/ it would also be worth including some more IPv6 examples in the examples (eg, for "https://[2001:db8::abcd]" as an example origin, perhaps augmenting the existing IPv4 examples so we always have both?)

4) Clarification on IP address matching
>For an IP address that appears in a URI-ID, the "host" component of both the reference identity and the presented identifier must match. These are parsed as either an "IP-literal" (following [[IPv6](https://www.rfc-editor.org/rfc/rfc4291)]) or an "IPv4address" (following [[IPv4](https://www.rfc-editor.org/rfc/rfc791)]). If the resulting octets are equal, the IP address matches.

In the IPv6 case, it may be better to reference https://datatracker.ietf.org/doc/html/rfc3986 section 3.2.2 since what is being matched isn't "IP-literal" (which is in square brackets) per the below ABNF but the address inside those brackets:

      IP-literal = "[" ( IPv6address / IPvFuture  ) "]"

There is also the case of https://www.rfc-editor.org/rfc/rfc6874 (which allows zoneids) but since the zoneid has host scope it makes no sense for it to be included in how certs are verified.  (But perhaps there should be a requirement that the IPv6 IP-ID address NOT be LinkLocal?)

**Comment by richsalz** [comment]
We already passed WGLC, and IETF LC, so yes, sorry, I think this is kinda too late.

**Comment by evyncke** [comment]
it is never really too late, e.g., sometimes an IESG DISCUSS ballot requires drastic changes.
Or in some recent cases (notably SVCB & ECH), an IESG approved document is modified, sent back to WGLC & IETF LC. 
Better a good delayed document sometimes.

**Comment by richsalz** [comment]
Sorry about that snarky comment, @enygren; @evyncke is right.  I'll just blame jetlag.
I posted to the thread with some proposed solutions.
See https://github.com/richsalz/draft-ietf-uta-rfc6125bis/pull/103
