### ISSUE TITLE
Lars's Feedback

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#104]
Lars Eggert has entered the following ballot position for
draft-ietf-uta-rfc6125bis-14: Discuss

When responding, please keep the subject line intact and reply to all
email addresses included in the To and CC lines. (Feel free to cut this
introductory paragraph, however.)

Please refer to https://urldefense.com/v3/__https://www.ietf.org/about/groups/iesg/statements/handling-ballot-positions/__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7uqdkd83$  
for more information about how to handle DISCUSS and COMMENT positions.

The document, along with other ballot positions, can be found here:
https://urldefense.com/v3/__https://datatracker.ietf.org/doc/draft-ietf-uta-rfc6125bis/__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7v4MXsmZ$

----------------------------------------------------------------------
DISCUSS:
----------------------------------------------------------------------

# GEN AD review of draft-ietf-uta-rfc6125bis-14

CC @larseggert

Thanks to Maria Ines Robles for the General Area Review Team (Gen-ART) review
(https://urldefense.com/v3/__https://mailarchive.ietf.org/arch/msg/gen-art/kKymWzL6jRgmCfLhf0A8IJATMMQ__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7ojHWKPN$ ).

### Section 4.2, paragraph 4
```
     Consider a SIP-accessible voice-over-IP (VoIP) server at the host
     voice.example.edu servicing SIP addresses of the form
     [user@voice.example.edu](mailto:user@voice.example.edu) and identified by a URI of
     <sip:voice.example.edu>.  A certificate for this service would
     include a URI-ID of sip:voice.example.edu (see [SIP-CERTS]) along
     with a DNS-ID of voice.example.edu.
```
This has got to be the most pedantic Discuss ever, but
AFAICT "example.edu" is not in fact a valid example domain, i.e.,
it's missing from
https://urldefense.com/v3/__https://www.iana.org/assignments/special-use-domain-names/special-use-domain-names.xhtml__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7h3lbvvu$

----------------------------------------------------------------------
COMMENT:
----------------------------------------------------------------------

### Inclusive language

Found terminology that should be reviewed for inclusivity; see
https://urldefense.com/v3/__https://www.rfc-editor.org/part2/*inclusive_language__;Iw!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7vzAs3Qk$  for background and more
guidance:

* Term `traditional`; alternatives might be `classic`, `classical`, `common`,
   `conventional`, `customary`, `fixed`, `habitual`, `historic`,
   `long-established`, `popular`, `prescribed`, `regular`, `rooted`,
   `time-honored`, `universal`, `widely used`, `widespread`

## Nits

All comments below are about very minor potential issues that you may choose to
address in some way - or ignore - as you see fit. Some were flagged by
automated tools (via https://urldefense.com/v3/__https://github.com/larseggert/ietf-reviewtool__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7lmUgeZH$ ), so there
will likely be some false positives. There is no need to let me know what you
did with these suggestions.

### Outdated references

Document references `draft-ietf-tls-subcerts`, but that has been published as
`RFC9345`.

### URLs

These URLs in the document can probably be converted to HTTPS:

*
https://urldefense.com/v3/__http://www.blackhat.com/presentations/bh-dc-09/Marlinspike/BlackHat-DC-09-Marlinspike-Defeating-SSL.pdf__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7ssUdH9o$

#### Section 4.1, paragraph 1
```
SIP as described in [SIP-SIPS]). Typically this identifier type would supple
                                 ^^^^^^^^^
```
A comma may be missing after the conjunctive/linking adverb "Typically".

#### Section 4.2, paragraph 4
```
s or IP-IDs. Again, because of multi-protocol attacks this practice is discou
                               ^^^^^^^^^^^^^^
```
This word is normally spelled as one.

#### Section 6.2, paragraph 7
```
DNS domain names more generally. Therefore the use of wildcard characters as
                                  ^^^^^^^^^
```
A comma may be missing after the conjunctive/linking adverb "Therefore".

## Notes

This review is in the ["IETF Comments" Markdown format][ICMF], You can use the
[`ietf-comments` tool][ICT] to automatically convert this review into
individual GitHub issues. Review generated by the [`ietf-reviewtool`][IRT].

[ICMF]: https://urldefense.com/v3/__https://github.com/mnot/ietf-comments/blob/main/format.md__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7qw6u-pu$
[ICT]: https://urldefense.com/v3/__https://github.com/mnot/ietf-comments__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7irKxvr-$
[IRT]: https://urldefense.com/v3/__https://github.com/larseggert/ietf-reviewtool__;!!GjvTz_vk!Vit0YEVafKcpWsWbgd21mvFM66UC5HmMCKEYoPinyYlFR07SOF0rCUr83MYYcONKCIEn7lmUgeZH$

**Comment by stpeter** [comment]
See email discussion. I think the use of `example.edu` is OK, since we previously cleared it with IANA.

**Comment by richsalz** [comment]
Will we keep getting questions about it?  Shrug. Pedantically correct is the best type of correct :) Additional commit undoing the change pushed.

**Comment by larseggert** [comment]
I wish IANA had bothered to actually register that with itself, rather than simply offering it on the side. I'll clear my discuss either way, but if there isn't a specific reason to use edu, why not use one of the properly registered ones?

**Comment by stpeter** [comment]
In RFC 6125 we wanted to show that the web, email, messaging, and voice services were each under the administrative control of different entities. If the use of `example.edu` makes people lose sleep, we could of course use company.example for web, ISP.example for email, app.example for messaging, and university.example for voice.

**Comment by stpeter** [comment]
@richsalz What do you think about using foo.example domains instead of example.foo domains? I am not wedded to the latter style, and I'm thinking the former might be clearer for the reader.

**Comment by richsalz** [comment]
no preference at all, happy to go with what you prefer.

**Comment by stpeter** [comment]
I think I'd like to make this change. I'll create a separate issue for it and then submit a PR against that issue.
