### ISSUE TITLE
Make spec work for peer-to-peer not just client-server

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#21]
Comment from Brian on the UTA list June 1:
   I think we should avoid mentioning roles like "client" or "server" except non-normatively to emphasize that the spec would apply to both roles. What matters is that the entity's identity is a DNS name.

**Comment by richsalz** [comment]
In the same thread, John Mattson said
- Some sections mention "server" while other sections does not state anything, therefor applying to both client and server. I think the draft needs to be very clear on this point.
- client certs are built with CN and cannot be easily changed. Other uses of RFC 6125 like the Service Based Architecture in 3GPP 5G makes little or no difference between server and client when it comes to certificates.

**Comment by stpeter** [comment]
The terminology of client and server in RFC 6125 refers to TLS clients and servers, which seems perfectly appropriate. Even in a peer-to-peer architecture, for any given TLS interaction one entity will be the TLS client and one will be the TLS server.

**Comment by richsalz** [comment]
Yeah, I get that it comes from TLS and that's fine.  But should make more clear, I think, that the server can validate the client identity (if presented)  As the text says "mutual TLS auth is ... [not often done] ..."

**Comment by richsalz** [comment]
Going to close this as at least the draft now makes an overall statement. I don't think we should change all uses of client and server since, as @stpeter said, it's the terminology used in TLS.  If there are specific uses that are wrong, we can fix those if they're pointed out.
