### ISSUE TITLE
is "*foo.example.com" allowed or just "*.example.com"

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#3]
WebPKI says just the latter. Browsers seem to do just the latter. OpenSSL allows the former, and then some.
WG needs to decide.

**Comment by sleevi** [comment]
See also https://datatracker.ietf.org/doc/html/rfc6125#section-7.2

**Comment by richsalz** [comment]
"As we’re not really using GitHub for discussion, please comment on this list."

https://mailarchive.ietf.org/arch/msg/uta/wwYRZ9PQu5YePavBzGwy1V_knNQ/
