### ISSUE TITLE
need a shorter title

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#35]
Perhaps something like `Naming services using TLS`

Or since "Naming services" might be confused with DNS or Grapevine, perhaps `Specifying and Verifying service names in TLS`

Or something.

**Comment by smyslov** [comment]
I strongly support the idea to make the title shorter. Currently it is too long, IMHO.

**Comment by richsalz** [comment]
Fixed with PR #36.
