### ISSUE TITLE
Don't mention XmppAddr

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#52]
Yaron
       * XMPP backward compatibility: does the XmppAddr still need to be 
       mentioned in -bis?

     Peter:
     For server certificates, that would be appropriate (see Section 
     13.7.1.2.1 of RFC 6120).

    Yaron:
    My question was: is it possible that we needed for *backward compatibility* 11 years ago
    may be outdated and ready to be obsoleted today.

**Comment by stpeter** [comment]
Fixed by https://github.com/richsalz/draft-ietf-uta-rfc6125bis/pull/50
