### ISSUE TITLE
reg-name in URIs

### ISSUE THREAD

**Issue by martinthomson** [richsalz/draft-ietf-uta-rfc6125bis#55]
The following text appears in [Section 6.2](https://richsalz.github.io/draft-ietf-uta-rfc6125bis/draft-ietf-uta-rfc6125bis.html#section-6.2-3.3):

> Matching only the "reg-name" rule from [[URI](https://richsalz.github.io/draft-ietf-uta-rfc6125bis/draft-ietf-uta-rfc6125bis.html#URI)] limits verification to DNS domain names, thereby differentiating a URI-ID from a uniformResourceIdentifier entry that contains an IP address or a mere host name, or that does not contain a "host" component at all.

This is not correct.  reg-name covers every type of hostname that isn't an IP address.  This includes DNS domain names, but it also includes other types of names ("a mere host name").  I plan to replace this text in #54, but I wanted to flag this separately.

**Comment by stpeter** [comment]
You are correct that this is an error, since the reg-name construction is defined as follows:

> reg-name    = *( unreserved / pct-encoded / sub-delims )

I'd suggest changing the text to:

> Matching only the "reg-name" rule from [URI] differentiates a URI-ID from a uniformResourceIdentifier entry that contains a host component matching the IP-literal rule or IPv4address rule.

**Comment by richsalz** [comment]
That text looks good.  We can make the change during AD/IESG review.

**Comment by aamelnikov** [comment]
After seeing that RFC 3986 contains:

   host        = IP-literal / IPv4address / reg-name

I agree.
