### ISSUE TITLE
08 draft contains spelling error "cetrificate"

### ISSUE THREAD

**Issue by OR13** [richsalz/draft-ietf-uta-rfc6125bis#69]
latest version here does not appear to have that error.

<img width="1053" alt="Screen Shot 2022-12-12 at 4 25 22 PM" src="https://user-images.githubusercontent.com/8295856/207168342-47e7424a-0356-4601-9fe4-512091004590.png">

**Comment by stpeter** [comment]
Already fixed in Markdown source.
