### ISSUE TITLE
08 (or its equivalent)

### ISSUE THREAD

**Issue by OR13** [richsalz/draft-ietf-uta-rfc6125bis#71]
> The scheme MUST be that of the protocol associated with the application service type and the "host" component (or its equivalent) MUST be the FQDN of the service.

Not sure I understand this part, but it feels like an underspecified MUST.

**Comment by stpeter** [comment]
It seems that this text was also in RFC 6125, but I cannot recall why. In URI syntax, there is no "equivalent" of a host component (i.e., nothing else allowed in an authority component that serves the same purpose as the host component). Therefore I suggest that we remove "(or its equivalent)".

**Comment by richsalz** [comment]
I agree with removal.
