### ISSUE TITLE
Browser behavior

### ISSUE THREAD

**Issue by sayrer** [richsalz/draft-ietf-uta-rfc6125bis#85]
The draft currently treats the WHATWG/browser behavior as an "alternative", but I think almost everything on the public internet works this way.

```
Although the reader should be aware that some applications (e.g., web browsers) might instead conform
to the Uniform Resource Locator (URL) specification maintained by the WHATWG [[URL]
(https://www.ietf.org/archive/id/draft-ietf-uta-rfc6125bis-10.html#URL)],
it is not expected that differences between the URI and URL specifications would manifest themselves in
certificate matching.
```

That's a little misleading, and contradicted by the IDNA section just below. There are names valid under `UTS-46` that aren't valid under `IDNA2008`.  The Postfix example given by Viktor Dukhovni is a good one:

https://mailarchive.ietf.org/arch/msg/uta/Nb_tFen5lDfoGoOgedwNS2KDc8A/

He says "To find substantially different practice, you probably need to look at industrial automation networks, and some IoT applications". That line of argument is definitely a pet peeve of mine, but I think it shows that that the browser way is what's really used.

**Comment by stpeter** [comment]
Take it to the list.
