### ISSUE TITLE
IP address octets

### ISSUE THREAD

**Issue by sayrer** [richsalz/draft-ietf-uta-rfc6125bis#86]
The draft says:

```
An IP address is either a 4-octet IPv4 address [[IPv4](https://www.ietf.org/archive/id/draft-ietf-uta-rfc6125bis-10.html#IPv4)] or a 16-octet IPv6 address [[IPv6](https://www.ietf.org/archive/id/draft-ietf-uta-rfc6125bis-10.html#IPv6)]. The identifier might need to be converted from a textual representation to obtain this value.
```

I think it should not mention the octet count, since this count is not necessarily true of IPv6 addresses (and does not appear in the IPv6 RFC). Suggested edit:

```
An IP address is either an IPv4 address [[IPv4](https://www.ietf.org/archive/id/draft-ietf-uta-rfc6125bis-10.html#IPv4)] or an IPv6 address [[IPv6](https://www.ietf.org/archive/id/draft-ietf-uta-rfc6125bis-10.html#IPv6)]. The identifier might need to be converted from a textual representation to obtain this value.
```

IPv6 addresses have all sorts of abbreviation mechanisms. I wrote this code, and it isn't quite right, although it's good enough for now:
https://github.com/sayrer/twitter-text/blob/cxx/rust/parser/src/twitter_text.pest#L166

It doesn't get zone indices right, but no one seems to care.

**Comment by richsalz** [comment]
I strongly disagree. IPaddresses, like DNS names, should be in canonical format when in certificates.

**Comment by sayrer** [comment]
Well, I get what you're saying here, I think. But, this is actually a total mess. For example, one might read

https://www.rfc-editor.org/rfc/rfc5952#section-4

and see the words "A recommendation for a canonical text representation format of IPv6 addresses is presented in this section." So, then the closing sentence "The identifier might need to be converted from a textual representation to obtain this value." is unclear.

**Comment by stpeter** [comment]
It's not our job to clean up the IP or DNS specs.
