### ISSUE TITLE
PKIX reference

### ISSUE THREAD

**Issue by sayrer** [richsalz/draft-ietf-uta-rfc6125bis#87]
The document says: "Many application technologies enable secure communication between two entities by means of Transport Layer Security (TLS) with Internet Public Key Infrastructure Using X.509 (PKIX) certificates."

But the PKIX reference is https://www.rfc-editor.org/rfc/rfc5280

Is that really right? If so, why?

**Comment by stpeter** [comment]
That's the standard IETF reference for PKIX.
