### ISSUE TITLE
Éric Vynke's feedback (2 of 2): Minor issues

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#99]
## Component or label ?

The text uses terms like `component of a domain name` while RFC 8499 (DNS
terminology) would prefer to use `label of a domain name`. Most parts of the
document correctly use 'labels' but there are some use of 'component'.

## Section 1.4.2

s/Certificates representing client identities other than as described above,
such as rfc822Name, are beyond the scope of this document/Certificates
representing client identities, such as rfc822Name, other than as described
above are beyond the scope of this document/ to simplify the parsing ?

# NITS

## Section 1.4.2

`for our purposes we care`, RFCs usually do not use a personal voice. But this
is a matter of taste.

**Comment by stpeter** [comment]
These edits seem straightforward and I will submit a PR for them.
